import { createHash } from "node:crypto";
import {
  copyFile,
  mkdir,
  readFile,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { apiHostPermission, deploymentConfig } from "./config.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = join(packageRoot, "src");
const runtimeFiles = Object.freeze([
  "LICENSE",
  "NOTICE",
  "capture-policy.js",
  "capture-result.js",
  "content-script.js",
  "icons/icon-128.png",
  "icons/icon-16.png",
  "icons/icon-32.png",
  "icons/icon-48.png",
  "pdf-fetcher.js",
  "popup.css",
  "popup.html",
  "popup.js",
  "service-worker.js",
]);

function outputArgument(argv) {
  if (argv.length !== 2 || argv[0] !== "--out" || !argv[1]) {
    throw new Error("Usage: node scripts/build.mjs --out <new-output-directory>");
  }
  return resolve(process.cwd(), argv[1]);
}

function sourcePath(path) {
  return path === "LICENSE" || path === "NOTICE"
    ? join(packageRoot, path)
    : join(sourceRoot, path);
}

async function assertRegularSource(path) {
  const metadata = await stat(path);
  if (!metadata.isFile()) throw new Error(`Build input is not a regular file: ${path}`);
}

async function copyRuntime(outputRoot) {
  for (const path of runtimeFiles) {
    const source = sourcePath(path);
    const destination = join(outputRoot, path);
    await assertRegularSource(source);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(source, destination);
  }
}

function configModule(config) {
  return [
    "// Generated by scripts/build.mjs. Do not edit.",
    `export const APP_ORIGIN = ${JSON.stringify(config.appOrigin)};`,
    `export const API_ORIGIN = ${JSON.stringify(config.apiOrigin)};`,
    "",
  ].join("\n");
}

async function build() {
  const outputRoot = outputArgument(process.argv.slice(2));
  const relativeOutput = relative(packageRoot, outputRoot);
  if (relativeOutput === "" || relativeOutput === ".") {
    throw new Error("The output directory must not be the source package root.");
  }
  if (!relativeOutput.startsWith("..")
      && relativeOutput !== "build"
      && !relativeOutput.startsWith(`build${sep}`)) {
    throw new Error("Output inside the source package is permitted only below build/.");
  }
  const config = deploymentConfig(process.env);
  const manifestPath = join(sourceRoot, "manifest.template.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  if (manifest.manifest_version !== 3
      || !Array.isArray(manifest.host_permissions)
      || manifest.host_permissions.length !== 0
      || Object.hasOwn(manifest, "key")) {
    throw new Error("The source manifest must remain an unbound, keyless MV3 template.");
  }

  await mkdir(dirname(outputRoot), { recursive: true });
  await mkdir(outputRoot, { recursive: false });
  await copyRuntime(outputRoot);

  manifest.host_permissions = [apiHostPermission(config.apiOrigin)];
  if (config.publicKey) manifest.key = config.publicKey;

  await writeFile(join(outputRoot, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, {
    encoding: "utf8",
    flag: "wx",
    mode: 0o644,
  });
  await writeFile(join(outputRoot, "config.js"), configModule(config), {
    encoding: "utf8",
    flag: "wx",
    mode: 0o644,
  });

  const reviewedSources = await Promise.all(runtimeFiles.map(async (path) => {
    const bytes = await readFile(join(outputRoot, path));
    return {
      path,
      bytes: bytes.length,
      sha256: createHash("sha256").update(bytes).digest("hex"),
    };
  }));
  const inventory = {
    schema_version: 1,
    extension_version: manifest.version,
    app_origin: config.appOrigin,
    api_origin: config.apiOrigin,
    api_host_permission: manifest.host_permissions[0],
    stable_public_key_supplied: Boolean(config.publicKey),
    reviewed_sources: reviewedSources,
  };
  await writeFile(join(outputRoot, "BUILD-INFO.json"), `${JSON.stringify(inventory, null, 2)}\n`, {
    encoding: "utf8",
    flag: "wx",
    mode: 0o644,
  });
}

await build();
