"""Structured evidence extraction: the data-charting step after screening.

For every included work the model fills the extraction fields (population,
method, sample size, outcomes, limitations by default) and must back each
value with a VERBATIM quote. Quotes are verified server-side against the
stored full text — the same fold-and-locate machinery as the grounded chat —
and a value whose quote cannot be located is marked unverified, never
silently trusted. Works without an acquired PDF fall back to the abstract,
labeled as such.
"""

import json
from typing import Any

from sixsentences_server.chat.service import _locate_quote, _norm_ws
from sixsentences_server.core.models import WorkRecord
from sixsentences_server.llm.base import TaskType
from sixsentences_server.llm.pool import LLMPool

DEFAULT_FIELDS = ["population", "method", "sample_size", "outcomes", "limitations"]

_EXTRACTION_SYSTEM = (
    "You extract structured evidence for a systematic review. Given one "
    "paper and a list of fields, answer with STRICT JSON only: "
    '{"fields": {"<field>": {"value": str, "quote": str, "page": int|null}}}. '
    "The value is a concise factual answer (or 'not reported'); the quote is "
    "one VERBATIM sentence copied from the text that supports the value "
    "(empty when not reported). Copy quotes exactly; never invent or "
    "paraphrase them."
)

_MAX_PAGES = 40
_MAX_BODY = 60_000


def extract_for_work(
    pool: LLMPool,
    fields: list[str],
    work: WorkRecord,
    pages: list[str],
) -> tuple[dict[str, Any], str]:
    """One work's evidence row: {field: {value, quote, page, verified, source}}
    plus the provider:model that produced it."""
    source = "fulltext" if pages else "abstract"
    if pages:
        body = "\n\n".join(
            f"[page {number}] {page}" for number, page in enumerate(pages[:_MAX_PAGES], start=1)
        )[:_MAX_BODY]
    else:
        body = work.abstract or "(no abstract available)"
    prompt = (
        f"Fields to extract: {json.dumps(fields)}\n\n"
        f"Title: {work.title}\nYear: {work.year or 'unknown'}\n"
        f"Venue: {work.venue or 'unknown'}\n\n{body}"
    )
    response = pool.complete(
        TaskType.CHAT, system=_EXTRACTION_SYSTEM, prompt=prompt, max_tokens=1800
    )
    raw = response.text.strip()
    if raw.startswith("```"):
        raw = raw.strip("`").removeprefix("json").strip()
    data = json.loads(raw).get("fields") or {}

    payload: dict[str, Any] = {}
    for field in fields:
        item = data.get(field) or {}
        value = str(item.get("value", "")).strip() or "not reported"
        quote = str(item.get("quote", "")).strip()
        located: int | None = None
        verified = False
        if quote and pages:
            claimed = item.get("page")
            start = claimed if isinstance(claimed, int) and claimed >= 1 else 1
            located = _locate_quote(quote, pages, start)
            if located is None:  # models misnumber pages; scan the whole text
                for candidate in range(1, len(pages) + 1, 3):
                    located = _locate_quote(quote, pages, candidate)
                    if located is not None:
                        break
            verified = located is not None
        elif quote:
            verified = _norm_ws(quote) in _norm_ws(work.abstract or "")
        payload[field] = {
            "value": value,
            "quote": quote,
            "page": located,
            "verified": verified,
            "source": source,
        }
    return payload, f"{response.provider}:{response.model}"


def _tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in value)


def render_extraction_tex(fields: list[str], rows: list[dict[str, Any]]) -> str:
    """The evidence table as a booktabs LaTeX table (paper-ready)."""
    headers = ["Study"] + [f.replace("_", " ").title() for f in fields]
    lines = [
        "% Evidence table generated by SixSentences_",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\caption{Evidence table of the included studies.}",
        "  \\label{tab:evidence}",
        "  \\small",
        "  \\begin{tabular}{@{}l" + "p{2.6cm}" * len(fields) + "@{}}",
        "    \\toprule",
        "    " + " & ".join(headers) + " \\\\",
        "    \\midrule",
    ]
    for row in rows:
        study = _tex_escape(f"{row['title'][:60]} ({row['year'] or 'n.d.'})")
        cells = [study]
        for field in fields:
            item = (row["payload"] or {}).get(field) or {}
            cells.append(_tex_escape(str(item.get("value", ""))[:220]))
        lines.append("    " + " & ".join(cells) + " \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)
